name: Deploy Ngrok VPS

on:
  workflow_dispatch:
    inputs:
      NGROK_API: 
        required: true 
      SSH_USERNAME: 
        required: true 
      SSH_PASSWORD: 
        required: true 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Tunnel Ngrok Vps
      env:
        NGROK_API: ${{ github.event.inputs.NGROK_API }}
        SSH_USERNAME: ${{ github.event.inputs.SSH_USERNAME }}
        SSH_PASSWORD: ${{ github.event.inputs.SSH_PASSWORD }}
      run: curl -sL https://raw.githubusercontent.com/V1HyperBot/add-vps/main/create-vps.sh | bash -s $NGROK_API $SSH_USERNAME $SSH_PASSWORD

    - name: Keep Online
      run: sleep infinity 
