name: Setup VPS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo systemctl start nginx

    - name: Print NGINX status
      run: sudo systemctl status nginx
