name: Ngrok VPS Setup

on: 
  push:
    branches: 
      - main

jobs:
  setup-vps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests library
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Get VPS using Ngrok API
      env:
        NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
        VPS_NAME: tomi
        VPS_PASSWORD: '@D4g88out5d'
      run: |
        python - <<EOF
        import requests

        api_key = "${{ env.NGROK_API_KEY }}"
        name = "${{ env.VPS_NAME }}"
        password = "${{ env.VPS_PASSWORD }}"

        url = "https://api.ngrok.com/endpoints"
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "name": name,
            "password": password,
            "protocol": "tcp",
            "addr": "22"
        }

        response = requests.post(url, headers=headers, json=payload)
        if response.status_code == 201:
            print("VPS created successfully")
            print(response.json())
        else:
            print("Failed to create VPS")
            print(response.text)
        EOF
