name: Deploy VPS using ngrok API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get ngrok VPS
      id: get-vps
      run: |
        curl -s -X POST "https://api.ngrok.com/v2/tunnels" \
        -H "Authorization: Bearer 2iscdz2Zuifmf1UO21OSSxEksMf_5RTq4Pih9xyfAN9EwmLHr" \
        -H "Content-Type: application/json" \
        -d '{
              "name": "my-vps",
              "proto": "tcp",
              "addr": "22"
            }' > ngrok_response.json

        jq . ngrok_response.json

    - name: Extract VPS info
      run: |
        NGROK_HOST=$(jq -r '.public_url' ngrok_response.json)
        NGROK_PORT=$(jq -r '.config.addr' ngrok_response.json)

        echo "NGROK_HOST=$NGROK_HOST" >> $GITHUB_ENV
        echo "NGROK_PORT=$NGROK_PORT" >> $GITHUB_ENV

    - name: Add username and password
      run: |
        USERNAME="admin"
        PASSWORD="password123"
        echo "USERNAME=$USERNAME" >> $GITHUB_ENV
        echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV

    - name: Output VPS details
      run: |
        echo "VPS Host: ${{ env.NGROK_HOST }}"
        echo "VPS Port: ${{ env.NGROK_PORT }}"
        echo "Username: ${{ env.USERNAME }}"
        echo "Password: ${{ env.PASSWORD }}"
