name: Deploy Ngrok VPS

on:
  workflow_dispatch:
    inputs:
      SSH_USERNAME: 
        required: true 
      SSH_PASSWORD: 
        required: true 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH User
      env:
        SSH_USERNAME: ${{ github.event.inputs.SSH_USERNAME }}
        SSH_PASSWORD: ${{ github.event.inputs.SSH_PASSWORD }}
      run: |
        sudo adduser --disabled-password --gecos "" $SSH_USERNAME --force-badname
        echo "$SSH_USERNAME:$SSH_PASSWORD" | sudo chpasswd
        sudo usermod -aG sudo $SSH_USERNAME

    - name: SSH Login
      run: |
        echo "SSH login information:"
        echo "Username: ${{ github.event.inputs.SSH_USERNAME }}"
        echo "Password: ${{ github.event.inputs.SSH_PASSWORD }}"
        echo "Hostname: $(hostname -I | cut -d' ' -f1)"
        sleep infinity
