name: Deploy Ngrok VPS

on:
  workflow_dispatch:
    inputs:
      NGROK_API: 
        required: true 
      SSH_USERNAME: 
        required: true 
      SSH_PASSWORD: 
        required: true 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: port-labs/port-github-action@v1
      with:
       clientId: ${{ secrets.CLIENT_ID }}
       clientSecret: ${{ secrets.CLIENT_SECRET }}
       operation: UPSERT
       identifier: port-github-action
       title: Port Github Action
       blueprint: PortIntegration
       properties: |
         {
           "version": "v1"
         }
       team: '["Port"]'
       relations: |
         {
           "deployedAt": "prod"
         }
